include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    require_trailing_commas: true
    directives_ordering: true
    always_use_package_imports: true
    use_build_context_synchronously: false
